In [2]:
%run ./../DataPrep/Load_Data.ipynb
from sklearn import preprocessing

In [3]:
df_total.drop(columns = ['JobLevel'],inplace = True)

In [4]:
classifier_variables = ['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement',
       'JobSatisfaction', 'MonthlyRate','OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StockOptionLevel','TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsWithCurrManager']

norm_col = ['MonthlyIncome','YearsSinceLastPromotion','TotalWorkingYears','NumCompaniesWorked']

binary_var = ['NonTravel','TravelRarely', 'TravelFrequently', 'D_R&D', 'D_Sales',
           'D_RH', 'E_LifeSciences','E_Medical','E_Marketing','E_TechnicalDegree',
              'E_RH','E_Other','Male','Female','Single','Married','Divorced']


df_norm = df_total.copy()

In [5]:
for cname in norm_col:
    
    df_norm[cname] = np.log(df_norm[cname]+1)

In [6]:
df_norm[classifier_variables] = preprocessing.power_transform(df_norm[classifier_variables], method='yeo-johnson')

In [7]:
df_norm

,Attrition,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobSatisfaction,MonthlyIncome,...,E_Medical,E_Marketing,E_TechnicalDegree,E_RH,E_Other,Male,Female,Single,Married,Divorced
0,1,-2.565934,-1.492207,-0.700347,0.040522,0.208597,-0.561151,0.326033,0.197856,7.259116,...,0,0,0,0,0,1,0,1,0,0
1,0,-2.565934,0.094651,0.479509,0.040522,1.209516,0.180838,-1.058710,0.197856,7.090910,...,1,0,0,0,0,0,1,1,0,0
2,1,-2.565934,1.199683,-0.230523,0.040522,-0.706596,0.180838,0.326033,-0.709062,7.538495,...,0,1,0,0,0,1,0,1,0,0
3,0,-2.565934,-1.309567,-0.230523,-0.916940,-0.706596,0.373380,0.326033,1.192743,6.958448,...,0,0,0,0,0,1,0,1,0,0
4,1,-2.565934,-1.436633,0.243416,-1.771185,0.208597,0.705687,0.326033,0.197856,7.552237,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,0,2.172817,-0.910092,0.105315,0.040522,-1.518118,-1.235882,0.326033,-1.509980,9.881600,...,0,0,0,0,0,0,1,0,1,0
1466,0,2.172817,1.600263,1.634493,0.040522,0.208597,0.705687,-1.058710,-1.509980,9.236690,...,0,1,0,0,0,0,1,0,1,0
1467,0,2.172817,0.927791,0.995187,1.082871,-1.518118,0.893121,0.326033,-1.509980,8.595265,...,0,1,0,0,0,1,0,1,0,0
1468,0,2.172817,-0.187724,0.105315,1.082871,-0.706596,-0.662801,2.014107,1.192743,8.560444,...,0,1,0,0,0,1,0,0,0,1
1469,0,2.172817,-1.059400,-1.494085,1.082871,0.208597,1.263094,-2.120625,1.192743,9.295049,...,1,0,0,0,0,1,0,0,0,1

In [8]:
df_total = df_norm